### ISSUE TITLE
[Bug] kodi crashes and closes whenever i attempt to refresh widgets

### ISSUE THREAD

**Issue by Mahava** [drinfernoo/plugin.program.autowidget#139]
run the refresh command 
get an error message
kodi closes

**To Reproduce**
1.  Go to '...'
2.  Click on '....'
3.  Scroll down to '....'
4.  See error

**Expected behavior**

**Screenshots**

**Details:**
kodi 19.4
Arctic horizon 2
windows 10 laptop
autowidget 3.70

clip from log:

2022-09-10 12:16:34.307 T:10764    INFO <general>: plugin.program.autowidget: Starting processing queue
2022-09-10 12:16:34.337 T:5460     INFO <general>: plugin.program.autowidget: +++++ REFRESHING AUTOWIDGETS +++++
2022-09-10 12:16:34.600 T:5460    ERROR <general>: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                                    - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                                   Error Type: <class 'AttributeError'>
                                                   Error Contents: 'NoneType' object has no attribute 'get'
                                                   Traceback (most recent call last):
                                                     File "C:\Users\XXXXX\AppData\Roaming\Kodi\addons\plugin.program.autowidget\service.py", line 4, in <module>
                                                       _monitor = refresh.RefreshService()
                                                     File "C:\Users\XXXXX\AppData\Roaming\Kodi\addons\plugin.program.autowidget\resources\lib\refresh.py", line 41, in __init__
                                                       self._update_widgets()
                                                     File "C:\Users\XXXXX\AppData\Roaming\Kodi\addons\plugin.program.autowidget\resources\lib\refresh.py", line 91, in _update_widgets
                                                       self._refresh(startup)
                                                     File "C:\Users\XXXXX\AppData\Roaming\Kodi\addons\plugin.program.autowidget\resources\lib\refresh.py", line 215, in _refresh
                                                       refresh_paths(notify=notification and not startup)
                                                     File "C:\Users\XXXXX\AppData\Roaming\Kodi\addons\plugin.program.autowidget\resources\lib\refresh.py", line 357, in refresh_paths
                                                       paths = refresh(
                                                     File "C:\Users\XXXXX\AppData\Roaming\Kodi\addons\plugin.program.autowidget\resources\lib\refresh.py", line 327, in refresh
                                                       path_label = manage.get_path_by_id(path_id, group_id).get(
                                                   AttributeError: 'NoneType' object has no attribute 'get'
                                                   -->End of Python script error report<--

**Comment by djay** [comment]
@drinfernoo I'm not sure if this is the way to fix it or not - https://github.com/drinfernoo/plugin.program.autowidget/pull/140. maybe more needs to be done?
