### ISSUE TITLE
Errors in logs

### ISSUE THREAD

**Issue by RandomGithubUsername** [drinfernoo/plugin.program.autowidget#63]
2020-11-16 16:02:13.535 T:13476  NOTICE: plugin.program.autowidget: Queue cache update for: aedfa7dc8bb713ba193af604ed8223934f383d24
2020-11-16 16:02:13.800 T:13483  NOTICE: plugin.program.autowidget: Wrote cache (exp in 299.795656919s): 48428d1ef29820c97c60924290e673541a69f97d
2020-11-16 16:02:14.055 T:13478  NOTICE: plugin.program.autowidget: [ action: merged ][ group: recently_added-1602388236.31 ][ mode: path ][ id: 23bc1887-4a36-4bf1-829f-3e92d392176c ]
2020-11-16 16:02:14.118 T:13478  NOTICE: plugin.program.autowidget: Read cache (exp in -1102140.15062s): fb598fe8b72a34f4c351e591867c58e624ff5544
2020-11-16 16:02:14.118 T:13478  NOTICE: plugin.program.autowidget: Queue cache update for: fb598fe8b72a34f4c351e591867c58e624ff5544
2020-11-16 16:02:14.225 T:13476  NOTICE: plugin.program.autowidget: Read cache (exp in -1419573.0702s): 6c7b2a438533047e3d6ec9eaabf84d81de5d6121
2020-11-16 16:02:14.225 T:13476  NOTICE: plugin.program.autowidget: Queue cache update for: 6c7b2a438533047e3d6ec9eaabf84d81de5d6121
2020-11-16 16:02:14.328 T:13478  NOTICE: plugin.program.autowidget: Read cache (exp in -1419562.41748s): cabdcdb2f5d83c095a59c06b875faa8c9cbcf022
2020-11-16 16:02:14.328 T:13478  NOTICE: plugin.program.autowidget: Queue cache update for: cabdcdb2f5d83c095a59c06b875faa8c9cbcf022
2020-11-16 16:02:14.353 T:13478   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.RuntimeError'>
                                            Error Contents: threads can only be started once
                                            Traceback (most recent call last):
                                              File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.program.autowidget/main.py", line 13, in <module>
                                                router.dispatch(_plugin, _handle, _params)
                                              File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.program.autowidget/resources/lib/common/router.py", line 71, in dispatch
                                                is_dir, category = menu.merged_path(group, widget_id)
                                              File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.program.autowidget/resources/lib/menu.py", line 455, in merged_path
                                                titles=titles, num=len(paths), merged=True)
                                              File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.program.autowidget/resources/lib/menu.py", line 235, in show_path
                                                files = refresh.get_files_list(path, titles, widget_id)
                                              File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.program.autowidget/resources/lib/refresh.py", line 233, in get_files_list
                                                queue_widget_update(widget_id)
                                              File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.program.autowidget/resources/lib/refresh.py", line 262, in queue_widget_update
                                                _thread.start()
                                              File "/home/jenkins/workspace/Android-ARM64-Leia/tools/depends/xbmc-depends/aarch64-linux-android-21-release/lib/python2.7/threading.py", line 730, in start
                                            RuntimeError: threads can only be started once
                                            -->End of Python script error report<--
2020-11-16 16:02:14.382 T:13487  NOTICE: plugin.program.autowidget: Wrote cache (exp in 299.769959927s): 2650229dcc162a8e57d4c8b1be043e0e49d75322
2020-11-16 16:02:14.486 T:13489  NOTICE: plugin.program.autowidget: Wrote cache (exp in 299.826649904s): 48428d1ef29820c97c60924290e673541a69f97d
2020-11-16 16:02:14.507 T:13487  NOTICE: plugin.program.autowidget: Wrote cache (exp in 299.911993027s): 2650229dcc162a8e57d4c8b1be043e0e49d75322
2020-11-16 16:02:14.921 T:13073   ERROR: GetDirectory - Error getting plugin://plugin.program.autowidget/?action=merged&group=recently_added-1602388236.31&mode=path&id=23bc1887-4a36-4bf1-829f-3e92d392176c&refresh=&reload=
2020-11-16 16:02:17.057 T:13495   ERROR: NEWADDON Unknown Video Info Key "progress

**Comment by drinfernoo** [comment]
Can you please post a full log?

**Comment by RandomGithubUsername** [comment]
2020-11-16 16:01:56.176 T:13375  NOTICE: plugin.program.autowidget: [ action: merged ][ group: recommendations-1602394726.31 ][ mode: path ][ id: 0f454d9e-0849-458b-997c-f4247308d304 ]
2020-11-16 16:01:56.176 T:13141  NOTICE: script.tv.show.next.aired --> Retrieving next airing episodes for all continuing Kodi tv shows...
2020-11-16 16:01:56.618 T:13375  NOTICE: plugin.program.autowidget: Read cache (exp in -1419558.61434s): aedfa7dc8bb713ba193af604ed8223934f383d24
2020-11-16 16:01:56.618 T:13375  NOTICE: plugin.program.autowidget: Queue cache update for: aedfa7dc8bb713ba193af604ed8223934f383d24
2020-11-16 16:01:57.037 T:13383  NOTICE: plugin.program.autowidget: Wrote cache (exp in 299.750613928s): 48428d1ef29820c97c60924290e673541a69f97d
2020-11-16 16:01:57.448 T:13382  NOTICE: plugin.program.autowidget: [ action: merged ][ group: recently_added-1602388236.31 ][ mode: path ][ id: 23bc1887-4a36-4bf1-829f-3e92d392176c ]
2020-11-16 16:01:57.816 T:13382  NOTICE: plugin.program.autowidget: Read cache (exp in -1102123.84874s): fb598fe8b72a34f4c351e591867c58e624ff5544
2020-11-16 16:01:57.816 T:13382  NOTICE: plugin.program.autowidget: Queue cache update for: fb598fe8b72a34f4c351e591867c58e624ff5544
2020-11-16 16:01:58.502 T:13375  NOTICE: plugin.program.autowidget: Read cache (exp in -1419557.34823s): 6c7b2a438533047e3d6ec9eaabf84d81de5d6121
2020-11-16 16:01:58.505 T:13375  NOTICE: plugin.program.autowidget: Queue cache update for: 6c7b2a438533047e3d6ec9eaabf84d81de5d6121
2020-11-16 16:01:58.884 T:13392  NOTICE: plugin.program.autowidget: Wrote cache (exp in 299.17446804s): 2650229dcc162a8e57d4c8b1be043e0e49d75322
2020-11-16 16:01:58.908 T:13382  NOTICE: plugin.program.autowidget: Read cache (exp in -1419546.99708s): cabdcdb2f5d83c095a59c06b875faa8c9cbcf022
2020-11-16 16:01:58.908 T:13382  NOTICE: plugin.program.autowidget: Queue cache update for: cabdcdb2f5d83c095a59c06b875faa8c9cbcf022
2020-11-16 16:01:59.707 T:13393  NOTICE: plugin.program.autowidget: Wrote cache (exp in 299.033314943s): 48428d1ef29820c97c60924290e673541a69f97d
2020-11-16 16:01:59.869 T:13394  NOTICE: plugin.program.autowidget: Wrote cache (exp in 299.221287012s): 2650229dcc162a8e57d4c8b1be043e0e49d75322
2020-11-16 16:02:01.927 T:13141  NOTICE: script.tv.show.next.aired --> Update complete
2020-11-16 16:02:06.179 T:13410   ERROR: NEWADDON Unknown Video Info Key "progress"
2020-11-16 16:02:10.802 T:13221   ERROR: Previous line repeats 49 times.
2020-11-16 16:02:10.802 T:13221  NOTICE: PLEX.utils: It took 0:00:16.936495 to run the function processing_loop_playstates
2020-11-16 16:02:10.845 T:13221  NOTICE: PLEX.utils: It took 0:00:23.001041 to run the function _run
2020-11-16 16:02:10.846 T:13221  NOTICE: PLEX.sync: Done initial sync on Kodi startup
2020-11-16 16:02:10.855 T:13221  NOTICE: PLEX.sync: Start downloading additional fanart with refresh False
2020-11-16 16:02:10.857 T:13446  NOTICE: PLEX.sync.fanart: Starting FanartThread
2020-11-16 16:02:10.876 T:13447  NOTICE: PLEX.artwork: ---===### Starting ImageCachingThread ###===---
2020-11-16 16:02:10.909 T:13074  NOTICE: My Music: Scanning for music info using worker thread, operation took 00:00
2020-11-16 16:02:10.918 T:13446  NOTICE: PLEX.sync.fanart: FanartThread finished: True
2020-11-16 16:02:10.930 T:13075  NOTICE: VideoInfoScanner: Starting scan ..
2020-11-16 16:02:12.011 T:13447  NOTICE: PLEX.artwork: ---===### Stopped ImageCachingThread ###===---
2020-11-16 16:02:12.108 T:13075  NOTICE: VideoInfoScanner: Finished scan. Scanning for video info took 00:01
2020-11-16 16:02:13.413 T:13476  NOTICE: plugin.program.autowidget: [ action: merged ][ group: recommendations-1602394726.31 ][ mode: path ][ id: 0f454d9e-0849-458b-997c-f4247308d304 ]
2020-11-16 16:02:13.535 T:13476  NOTICE: plugin.program.autowidget: Read cache (exp in -1419575.53147s): aedfa7dc8bb713ba193af604ed8223934f383d24
2020-11-16 16:02:13.535 T:13476  NOTICE: plugin.program.autowidget: Queue cache update for: aedfa7dc8bb713ba193af604ed8223934f383d24
2020-11-16 16:02:13.800 T:13483  NOTICE: plugin.program.autowidget: Wrote cache (exp in 299.795656919s): 48428d1ef29820c97c60924290e673541a69f97d
2020-11-16 16:02:14.055 T:13478  NOTICE: plugin.program.autowidget: [ action: merged ][ group: recently_added-1602388236.31 ][ mode: path ][ id: 23bc1887-4a36-4bf1-829f-3e92d392176c ]
2020-11-16 16:02:14.118 T:13478  NOTICE: plugin.program.autowidget: Read cache (exp in -1102140.15062s): fb598fe8b72a34f4c351e591867c58e624ff5544
2020-11-16 16:02:14.118 T:13478  NOTICE: plugin.program.autowidget: Queue cache update for: fb598fe8b72a34f4c351e591867c58e624ff5544
2020-11-16 16:02:14.225 T:13476  NOTICE: plugin.program.autowidget: Read cache (exp in -1419573.0702s): 6c7b2a438533047e3d6ec9eaabf84d81de5d6121
2020-11-16 16:02:14.225 T:13476  NOTICE: plugin.program.autowidget: Queue cache update for: 6c7b2a438533047e3d6ec9eaabf84d81de5d6121
2020-11-16 16:02:14.328 T:13478  NOTICE: plugin.program.autowidget: Read cache (exp in -1419562.41748s): cabdcdb2f5d83c095a59c06b875faa8c9cbcf022
2020-11-16 16:02:14.328 T:13478  NOTICE: plugin.program.autowidget: Queue cache update for: cabdcdb2f5d83c095a59c06b875faa8c9cbcf022
2020-11-16 16:02:14.353 T:13478   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.RuntimeError'>
                                            Error Contents: threads can only be started once
                                            Traceback (most recent call last):
                                              File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.program.autowidget/main.py", line 13, in <module>
                                                router.dispatch(_plugin, _handle, _params)
                                              File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.program.autowidget/resources/lib/common/router.py", line 71, in dispatch
                                                is_dir, category = menu.merged_path(group, widget_id)
                                              File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.program.autowidget/resources/lib/menu.py", line 455, in merged_path
                                                titles=titles, num=len(paths), merged=True)
                                              File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.program.autowidget/resources/lib/menu.py", line 235, in show_path
                                                files = refresh.get_files_list(path, titles, widget_id)
                                              File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.program.autowidget/resources/lib/refresh.py", line 233, in get_files_list
                                                queue_widget_update(widget_id)
                                              File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.program.autowidget/resources/lib/refresh.py", line 262, in queue_widget_update
                                                _thread.start()
                                              File "/home/jenkins/workspace/Android-ARM64-Leia/tools/depends/xbmc-depends/aarch64-linux-android-21-release/lib/python2.7/threading.py", line 730, in start
                                            RuntimeError: threads can only be started once
                                            -->End of Python script error report<--
2020-11-16 16:02:14.382 T:13487  NOTICE: plugin.program.autowidget: Wrote cache (exp in 299.769959927s): 2650229dcc162a8e57d4c8b1be043e0e49d75322
2020-11-16 16:02:14.486 T:13489  NOTICE: plugin.program.autowidget: Wrote cache (exp in 299.826649904s): 48428d1ef29820c97c60924290e673541a69f97d
2020-11-16 16:02:14.507 T:13487  NOTICE: plugin.program.autowidget: Wrote cache (exp in 299.911993027s): 2650229dcc162a8e57d4c8b1be043e0e49d75322
2020-11-16 16:02:14.921 T:13073   ERROR: GetDirectory - Error getting plugin://plugin.program.autowidget/?action=merged&group=recently_added-1602388236.31&mode=path&id=23bc1887-4a36-4bf1-829f-3e92d392176c&refresh=&reload=
2020-11-16 16:02:17.057 T:13495   ERROR: NEWADDON Unknown Video Info Key "progress"
2020-11-16 16:03:53.106 T:13042   ERROR: Previous line repeats 49 times.
2020-11-16 16:03:53.106 T:13042  NOTICE: Samba is idle. Closing the remaining connections

**Comment by drinfernoo** [comment]
Could you please post a full log? 🤦🏽‍♂️

**Comment by djay** [comment]
@drinfernoo fixed in that latest PR. no longer uses threading.
