### ISSUE TITLE
Some Groups fail to load and disappear

### ISSUE THREAD

**Issue by muenzerr** [drinfernoo/plugin.program.autowidget#71]
I am setting up a media center from a collection of sources. I added now a bunch of documentaries as several groups (called "Dokus 0" - "Dokus 7"). However some of these groups (for example "Dokus 3") often fail to load and disappear from the screen.  

I attached the log. I think lines 1827 ff. and line 1846 may give a hint what's wrong.

Link to the log:
https://paste.kodi.tv/acivexeguy.kodi

**Comment by djay** [comment]
The exception is 

```
2021-01-10 23:47:27.879 T:1915834384   DEBUG: CDirectoryProvider[plugin://plugin.program.autowidget/?action=cycling&group=dokus_4-1610314666.18&mode=path&id=3be329f8-a0d3-402c-a939-94d90f68edd3&refresh=1610318847.85&reload=]: refreshing..
2021-01-10 23:47:27.885 T:1538236640   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.KeyError'>
                                            Error Contents: 'art'
                                            Traceback (most recent call last):
                                              File "/home/osmc/.kodi/addons/plugin.program.autowidget/main.py", line 13, in <module>
                                                router.dispatch(_plugin, _handle, _params)
                                              File "/home/osmc/.kodi/addons/plugin.program.autowidget/resources/lib/common/router.py", line 69, in dispatch
                                                is_dir, category = menu.path_menu(group, action, widget_id)
                                              File "/home/osmc/.kodi/addons/plugin.program.autowidget/resources/lib/menu.py", line 414, in path_menu
                                                titles, cat = show_path(group_id, _label, widget_id, widget_path)
                                              File "/home/osmc/.kodi/addons/plugin.program.autowidget/resources/lib/menu.py", line 317, in show_path
                                                art=file['art'],
                                            KeyError: 'art'
                                            -->End of Python script error report<--
2021-01-10 23:47:27.897 T:1538236640   DEBUG: onExecutionDone(17, /home/osmc/.kodi/addons/plugin.program.autowidget/main.py)
```
so I guess the code needs to make less assumptions about whats available?

**Comment by drinfernoo** [comment]
This is an issue of using old (1.x) groups with versions greater than 2.0. Recreate your groups.

**Comment by muenzerr** [comment]
I will try that. But i am 100% sure I created the Groups with the newest version, so there must be another reason than what you suggest.
