### ISSUE TITLE
Widget not working after copy pasting widget files from a backup

### ISSUE THREAD

**Issue by patel-jeel92** [drinfernoo/plugin.program.autowidget#90]
I am running Kodi 19 and AutoWidget 3.1.8 and I have an old backup of autowidgets and manually copy pasted some .widget and .group files into the userdata/addon/plugin.program.autowidget directory. Then when I open AutoWidget and then try opening up active widgets, I get an error. The error from the log is shown. I have also attached a couple .widget and .group files.

Log snippet:
```2021-06-07 23:07:02.613 T:30469   ERROR <general>: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                                    - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                                   Error Type: <class 'UnicodeDecodeError'>
                                                   Error Contents: 'utf-8' codec can't decode byte 0xb0 in position 37: invalid start byte
                                                   Traceback (most recent call last):
                                                     File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.program.autowidget/main.py", line 13, in <module>
                                                       router.dispatch(_plugin, _handle, _params)
                                                     File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.program.autowidget/resources/lib/common/router.py", line 76, in dispatch
                                                       is_dir, is_category = menu.active_widgets_menu()
                                                     File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.program.autowidget/resources/lib/menu.py", line 127, in active_widgets_menu
                                                       widgets = sorted(manage.clean(all=True),
                                                     File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.program.autowidget/resources/lib/manage.py", line 13, in clean
                                                       for widget in find_defined_widgets():
                                                     File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.program.autowidget/resources/lib/manage.py", line 197, in find_defined_widgets
                                                       widget_def = utils.read_json(os.path.join(utils._addon_path, widget_file))
                                                     File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.program.autowidget/resources/lib/common/utils.py", line 297, in read_json
                                                       content = six.ensure_text(f.read())
                                                     File "/data/user/0/org.xbmc.kodi/cache/apk/assets/python3.8/lib/python3.8/codecs.py", line 701, in read
                                                       return self.reader.read(size)
                                                     File "/data/user/0/org.xbmc.kodi/cache/apk/assets/python3.8/lib/python3.8/codecs.py", line 504, in read
                                                       newchars, decodedbytes = self.decode(data, self.errors)
                                                   UnicodeDecodeError: 'utf-8' codec can't decode byte 0xb0 in position 37: invalid start byte
                                                   -->End of Python script error report<--
                                                   
2021-06-07 23:07:03.993 T:30469    INFO <general>: Python interpreter stopped
2021-06-07 23:07:04.007 T:30467   ERROR <general>: GetDirectory - Error getting plugin://plugin.program.autowidget/?mode=widget&refresh&reload
2021-06-07 23:07:04.020 T:28042   ERROR <general>: CGUIMediaWindow::GetDirectory(plugin://plugin.program.autowidget/?mode=widget&refresh&reload) failed
```

Widget File: (Had to add .txt extension for upload)
[e8867178-9480-4370-8340-5f638ae57475.widget.txt](https://github.com/drinfernoo/plugin.program.autowidget/files/6613416/e8867178-9480-4370-8340-5f638ae57475.widget.txt)

Group File: (Had to add .txt extension for upload)
[shows_-_popular-1612652124.45.group.txt](https://github.com/drinfernoo/plugin.program.autowidget/files/6613419/shows_-_popular-1612652124.45.group.txt)

**Comment by drinfernoo** [comment]
I would need to have a full log file, and a backup of your groups (can be done from AutoWidget's settings), in order to see which group is failing. It appears that neither of the files you've attached are the culprit, as neither one contains any Unicode characters for AutoWidget to choke on in the first place.

**Comment by patel-jeel92** [comment]
The groups I am trying to paste are from this link https://www.reddit.com/r/Addons4Kodi/comments/lhdyul/kodiflix_made_a_netflix_titan_bingie_mod_build/. The guy has a build that he links, I just unzipped the file and copied all the groups he had inside the autowidget folder and pasted them into userdata/addon_data/plugin.program.autowidget directory. Here is the zip folder with all the groups and widgets

[widgets.zip](https://github.com/drinfernoo/plugin.program.autowidget/files/6690014/widgets.zip)
